assets:
  - livithealth.sql.gz
image: proboci/ubuntu-16.04-lamp:php-7.0
steps:
  - name: Drupal 7 Probo site setup.
    plugin: Drupal
    drupalVersion: 7
    subDirectory: docroot
    databaseEngine: mysql
    database: livithealth.sql.gz
    databaseGzipped: true
    phpIniOptions:
      post_max_size: 25M
      memory_limit: 256M
      all:
        upload_max_filesize: 26M
      apache2:
        error_reporting: E_ALL ~E_DEPRECATED
      cli:
        error_reporting: E_ALL
    mysqlCnfOptions:
      innodb_file_per_table: 1
    varnish:
      enable: false
