steps:
  - name: Drupal 7 Probo site setup.
    plugin: Drupal
    drupalVersion: 7
    subDirectory: docroot
    phpIniOptions:
      upload_max_filesize: 26M
      post_max_size: 25M
      memory_limit: 256M
    mysqlCnfOptions:
      innodb_file_per_table: 1
    varnish:
      enable: false
