---
assets:
  - daily_livithealth_2018-10-29_08h54m_Monday.sql.gz
  - credentials.sh
image: proboci/ubuntu-16.04-lamp:php-7.0-beta
steps:
  -
    name: Drupal 7 Probo site setup.
    plugin: Drupal
    drupalVersion: 7
    database: daily_livithealth_2018-10-29_08h54m_Monday.sql.gz
    databaseName: mydbb
    databaseUser: mydbuser
    databaseGzipped: true
    subDirectory: docroot
    phpIniOptions:
      post_max_size: 25M
      memory_limit: 256M
      all:
        upload_max_filesize: 26M
      apache2:
        error_reporting: E_ALL ~E_DEPRECATED
      cli:
        error_reporting: E_ALL
    mysqlCnfOptions:
      innodb_file_per_table: 1
    varnish:
      enable: false
