image: proboci/ubuntu-14.04-lamp:php-7.1
steps:
  - name: Hello World
    command: 'echo "Hello Probo pal. If you are reading this output you have your first successful Probo build step. Probo gives you a fresh environment for each build, so you can run whatever you want. This build step is using the default Probo build plugin: Shell."'
  - name: Checking ubuntu, apache, mysql, and php version.
    plugin: Script
    script:
      - lsb_release -a
      - mysql --version
      - apache2 -version
      - php -v
  - name: Probo site setup
    plugin: Drupal
    runInstall: true
    profileName: standard
    clearCaches: false
    varnish: true
  - name: Hello Again
    command: 'echo "You can use Probo to run automated tests like the previous step did. Or not. Probo is useful with or without tests."'
