assets:
  - pgsql.sql
image: proboci/ubuntu-14.04-lamp:php-5.5-beta
steps:
  - name: Drupal 7 Probo site setup.
    plugin: Drupal
    drupalVersion: 7
    subDirectory: docroot
    databaseEngine: pgsql
    database: pgsql.sql
    phpIniOptions:
      post_max_size: 25M
      memory_limit: 256M
      all:
        upload_max_filesize: 26M
      apache2:
        error_reporting: E_ALL ~E_DEPRECATED
      cli:
        error_reporting: E_ALL
    mysqlCnfOptions:
      innodb_file_per_table: 1
    varnish:
      enable: false
  - name: Break
    plugin: Shell
    command: mkdir /root/pup/pop
