image: proboci/ubuntu-16.04-lamp:php7.2-nightly
phpIniOptions:
  upload_max_filesize: 25M
  post_max_size: 25M
  memory_limit: 256M
mysqlCnfOptions:
  innodb_file_per_table: off
steps:
  - name: Drupal 7 Probo site setup.
    plugin: Drupal
    drupalVersion: 7
    subDirectory: docroot
